name: SQ-build

on:
  release:
    types: [published]
    
jobs:
  
  build:    
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1  
      
      - name: Configure Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          
      - name: install capnproto
        run: |
          curl https://capnproto.org/capnproto-c++-win32-0.10.3.zip -o "capnp.zip"
          Expand-Archive capnp.zip -DestinationPath C:\capnp
    
      - name: build sq
        run: |
          $env:PATH = $env:PATH + ";C:\capnp\capnproto-tools-win32-0.10.3"
          echo ${env:PATH}
          git clone -b v0.30.1 https://gitlab.com/sequoia-pgp/sequoia-sq.git sequoia
          cd sequoia
          cargo build --release --no-default-features --features crypto-cng

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: sequoia-sq_x64
          if-no-files-found: ignore
          path: |
            sequoia\target\release\sq.exe
            sequoia\target\release\sq.pdb
